/*
{
 
    "fork": false,
    "forks_url": "https://api.github.com/repos/binarywang/java-testdata-generator/forks",
    "tags_url": "https://api.github.com/repos/binarywang/java-testdata-generator/tags",
    "languages_url": "https://api.github.com/repos/binarywang/java-testdata-generator/languages",
    "contributors_url": "https://api.github.com/repos/binarywang/java-testdata-generator/contributors",
    "subscribers_url": "https://api.github.com/repos/binarywang/java-testdata-generator/subscribers",
    "subscription_url": "https://api.github.com/repos/binarywang/java-testdata-generator/subscription",
    "commits_url": "https://api.github.com/repos/binarywang/java-testdata-generator/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/binarywang/java-testdata-generator/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/binarywang/java-testdata-generator/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/binarywang/java-testdata-generator/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/binarywang/java-testdata-generator/contents/{+path}",
    "compare_url": "https://api.github.com/repos/binarywang/java-testdata-generator/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/binarywang/java-testdata-generator/merges",
    "archive_url": "https://api.github.com/repos/binarywang/java-testdata-generator/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/binarywang/java-testdata-generator/downloads",
    "issues_url": "https://api.github.com/repos/binarywang/java-testdata-generator/issues{/number}",
    "pulls_url": "https://api.github.com/repos/binarywang/java-testdata-generator/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/binarywang/java-testdata-generator/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/binarywang/java-testdata-generator/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/binarywang/java-testdata-generator/labels{/name}",
    "releases_url": "https://api.github.com/repos/binarywang/java-testdata-generator/releases{/id}",
    "deployments_url": "https://api.github.com/repos/binarywang/java-testdata-generator/deployments",
    "created_at": "2016-01-21T05:45:44Z",
    "updated_at": "2022-07-28T09:01:50Z",
    "pushed_at": "2022-06-21T11:43:14Z",
    "git_url": "git://github.com/binarywang/java-testdata-generator.git",
    "ssh_url": "git@github.com:binarywang/java-testdata-generator.git",
    "clone_url": "https://github.com/binarywang/java-testdata-generator.git",
    "svn_url": "https://github.com/binarywang/java-testdata-generator",
    "homepage": "",
    "size": 111,
    "stargazers_count": 488,
    "watchers_count": 488,
    "language": "Java",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 248,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": null,
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [
        "java",
        "test"
    ],
    "visibility": "public",
    "forks": 248,
    "open_issues": 0,
    "watchers": 488,
    "default_branch": "master",
    "score": 1
}
   "owner": {
        "login": "binarywang",
        "id": 1343140,
        "node_id": "MDQ6VXNlcjEzNDMxNDA=",
        "avatar_url": "https://avatars.githubusercontent.com/u/1343140?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/binarywang",
        "html_url": "https://github.com/binarywang",
        "followers_url": "https://api.github.com/users/binarywang/followers",
        "following_url": "https://api.github.com/users/binarywang/following{/other_user}",
        "gists_url": "https://api.github.com/users/binarywang/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/binarywang/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/binarywang/subscriptions",
        "organizations_url": "https://api.github.com/users/binarywang/orgs",
        "repos_url": "https://api.github.com/users/binarywang/repos",
        "events_url": "https://api.github.com/users/binarywang/events{/privacy}",
        "received_events_url": "https://api.github.com/users/binarywang/received_events",
        "type": "User",
        "site_admin": false
    },
*/

