export default {
    USERS_FETCH: "USERS_FETCH",
    USERS_LOAD: "USERS_LOAD",
    USERS_CLEAR_SEARCH: "USERS_CLEAR_SEARCH",
    USER_FETCH_INFO: "USER_FETCH_INFO",
    USER_LOAD_INFO: "USER_LOAD_INFO",

    //Global

    GLOBAL_SHOW_NOTIFICATION: "GLOBAL_SHOW_NOTIFICATION",
    GLOBAL_CLOSE_NOTIFICATION: "GLOBAL_CLOSE_NOTIFICATION",
    GLOBAL_FETCH_RATE_LIMIT: "GLOBAL_FETCH_RATE_LIMIT",
    GLOBAL_LOAD_RATE_LIMIT: "GLOBAL_LOAD_RATE_LIMIT",
};
