export default {
    USERS_FETCH: "USERS_FETCH",
    USERS_LOAD: "USERS_LOAD",
    USERS_CLEAR_SEARCH: "USERS_CLEAR_SEARCH",


    //Global

    GLOBAL_SHOW_NOTIFICATION:"GLOBAL_SHOW_NOTIFICATION",
};
